orbs:
  docker: circleci/docker@1.6.0
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/hadolint:
          ignore-rules: "DL3007,DL3008,DL3015"
      - docker/publish:
          registry: docker.io
          image: attilanagynet/kalilinux
          update-description: true
          tag: latest
          filters:
            branches:
              only:
                - main
          requires:
            - docker/hadolint
