name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.io/attilanagynet/kalilinux:latest
    - name: Docker Login
      run: docker login -u attilanagynet -p ${{secrets.DOCKER_PASSWORD}}
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    - name: Push to Registry
      run: docker push  docker.io/attilanagynet/kalilinux:latest
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}